name: publish

on: [push]

jobs:
  publish-golang-app-image:
    runs-on: ubuntu-latest
    env:
    CR_PAT: ${{ secret.CR_PAT }}

    steps:
      - uses: actions/checkout@v2
      - name: Build the golang-app Docker image
        run: |
          echo $CR_PAT | docker login ghcr.io -u YourAccountOrGHOrgaNameHere --password-stdin
